name: Deployment

on:
  push:
    branches:
      - main

jobs:
  initplan:
    runs-on: docker.mirror.hashicorp.services/hashicorp/terraform:light
    environment: stg
    steps:
      - name: initplan
        run: |
          terraform init -input=false
          terraform workspace select stg
          terraform plan -out tfapply
        