name: Deployment

on:
  push:
    branches:
      - main

jobs:
  plan-stg:
    runs-on: ubuntu-latest
    permissions:
      pull-request: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: validate
        run: |
          terraform workspace select stg
          terraform plan -out tfapply-stg

  deploy-stg:
    runs-on: ubuntu-latest
    permissions:
      pull-request: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
    environment: stg
    needs: plan-stg
    steps:
      - name: Terraform Plan
        id: plan
        run: 

  plan-prd:
    runs-on: ubuntu-latest
    permissions:
      pull-request: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: |
          terraform workspace select prd
          terraform plan -out tfapply-prd
  
  deploy-prod:
    runs-on: ubuntu-latest
    permissions:
      pull-request: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
    environment: prd
    needs: [plan-prd,  deploy-stg]
    steps:
      - name: Terraform Plan
        id: plan
        run: terraform apply -auto-approve tfapply-prd